highlight jsGlobalObjects ctermfg=203 guifg=#ff5f5f 
highlight jsExtendsKeyword  ctermfg=203 guifg=#ff5f5f
highlight jsBooleanTrue  ctermfg=203 guifg=#ff5f5f
highlight jsBooleanFalse  ctermfg=203 guifg=#ff5f5f
highlight jsNull  ctermfg=203 guifg=#ff5f5f
hi! link jsStorageClass GruvboxYellow
hi! link jsOperator GruvboxRed
hi! link jsFunction GruvboxYellow
hi! link jsClassKeyword GruvboxYellow
hi! link jsClassDefinition GruvboxFg0
hi! link jsTernaryIfOperator GruvboxRed
