#! /bin/sh

$HOME/.config/polybar/launch.sh
$HOME/.scripts/rsim.sh
$HOME/.fehbg

picom -b --experimental-backends --backend glx
pgrep -x sxhkd > /dev/null || sxhkd &
light-locker > /dev/null &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap          15
bspc config border_width         6
bspc config focused_border_color '#555566'

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a feh state=floating
bspc rule -a Zathura state=tiled
