#!/bin/sh

$HOME/.fehbg
picom -b

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output eDP --mode 1680x1050 &

bspc config window_gap           6
bspc config border_width         4
bspc config focused_border_color '#A0153E'

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config merge_overlapping_monitors true

bspc monitor -d I II III IV # V VI VII VIII IX X

bspc rule -a feh state=floating
bspc rule -a albert:albert border=off focus=on

albert &
polybar &
light-locker &
